import Link from 'next/link'
import { ActionBand, SiteShell, StatStrip } from '@/components/site-shell'
import { studentProfiles } from '@/lib/student-profiles'

export default function Home() {
  return <SiteShell>
    <section className="hero hero-richie"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><i /> 2027 GOVERNOR · NAKURU COUNTY</p><h1>RICHIE GITHATU<br /><em>Nakuru Kwetu.</em></h1><p className="hero-kicker">New Generation leadership for Nakuru County</p><p className="hero-text">Richie Githatu is running for Governor of Nakuru County in 2027 — with a practical agenda for opportunity, accountable leadership, and a county that works for everyone.</p><div className="hero-actions"><Link href="/about" className="button button-primary">Meet Richie Githatu <span>↗</span></Link><Link href="/students" className="button button-secondary">Adopt a student <span>↗</span></Link><Link href="/manifesto" className="text-link">Read the agenda <span>→</span></Link></div><div className="hero-election-badge"><strong>2027</strong><span>YOUR VOICE<br />YOUR CHOICE</span></div><div className="promise"><b>032</b><span><strong>Linda Nakuru.</strong><br />Nakuru Kwetu · New Generation</span></div></div><div className="hero-visual hero-cutout"><div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" /><img src="/richie-cutout.png" alt="Richie Githatu in a white shirt" /><div className="floating-note"><b>NAKURU</b><span>KWETU.</span></div><div className="hero-signature">Richie Githatu</div></div></div></section>

    <section className="programme-banner programme-feature"><div className="container programme-banner-inner"><div className="programme-mark">01</div><div><p className="eyebrow">ADOPT-A-STUDENT PROGRAMME</p><h2>No bright mind<br /><em>left behind.</em></h2><p>Stand with a determined Nakuru student. Start with KSh 10 and help turn education into a real future.</p></div><Link href="/students" className="button button-primary">Support a student <span>↗</span></Link></div></section>

    <section className="section students students-home"><div className="container"><div className="section-heading"><div><p className="eyebrow"><i /> ADOPT-A-STUDENT PROGRAMME</p><h2>Adopt a Student<br /><em>Programme.</em></h2></div><p>Your support goes directly toward keeping bright minds in class and moving toward their calling.</p></div><div className="student-grid">{studentProfiles.map(student => <Link href={`/students/${student.slug}`} className="student-card student-card-link" key={student.slug}><div className="student-image"><img src={student.image} alt={student.name} /><span>{student.number} · {student.tag.toUpperCase()}</span></div><div className="student-body"><span className="label">{student.name.toUpperCase()}</span><h3>{student.school}</h3><p>{student.short}</p><div className="student-details"><span>PAYBILL <b>{student.paybill}</b></span><span>ACCOUNT <b>{student.account}</b></span></div><div className="need"><b>{student.need}</b><span>needed to continue</span></div><span className="card-link">View full profile <span>→</span></span></div></Link>)}</div><div className="center-link"><Link href="/students" className="text-link">See all student profiles <span>→</span></Link></div></div></section>

    <StatStrip items={[{ value: '2027', label: 'Governor for Nakuru County' }, { value: '032', label: 'Nakuru County' }, { value: 'KSh 10', label: 'a simple way to begin' }, { value: 'Your voice', label: 'your power' }]} />

    <section className="section voter-section"><div className="container voter-quote"><p className="eyebrow">A MESSAGE FOR NAKURU</p><blockquote>“If you are eligible to vote, register. Your voice is your power, and your participation will help shape Nakuru County&apos;s future in 2027.”</blockquote><cite>— Richie Githatu</cite></div></section>

    <section className="section about-feature"><div className="container about-feature-grid"><div className="about-cutout"><div className="about-circle" /><img src="/richie-seated-cutout.png" alt="Richie Githatu seated and smiling" /><span>TOGETHER<br /><b>WE RISE.</b></span></div><div className="about-feature-copy"><p className="eyebrow">ABOUT RICHIE GITHATU</p><h2>Together we rise.<br /><em>Leadership opens doors.</em></h2><p>Leadership begins with showing up: listening closely, opening doors, and believing in the people who make Nakuru home.</p><p>Richie Githatu brings a new-generation spirit to public service — practical, warm, and focused on turning ideas into opportunity.</p><Link href="/about" className="button button-primary">Read about Richie <span>↗</span></Link></div></div></section>

    <section className="section feature-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">THE AGENDA</p><h2>Ideas that move<br /><em>people forward.</em></h2></div><p>Focused action. Clear accountability. A better county built together.</p></div><div className="feature-grid"><Link href="/manifesto" className="feature-card feature-card-dark"><span>01 · YOUTH</span><h3>From tender<br />to opportunity.</h3><p>2,840 paid first chances through Vijana na Tender.</p><b>Explore the policy →</b></Link><Link href="/students" className="feature-card feature-card-blue"><span>02 · EDUCATION</span><h3>No bright mind<br />left behind.</h3><p>Direct support for students who are determined to finish.</p><b>Meet the students →</b></Link><Link href="/join" className="feature-card feature-card-red"><span>03 · MOVEMENT</span><h3>One county.<br />One future.</h3><p>Bring your voice, skill, and energy to Nakuru&apos;s next chapter.</p><b>Join us →</b></Link></div></div></section>

    <section className="section support-section"><div className="container support-grid"><div><p className="eyebrow">SUPPORT THE MOVEMENT</p><h2>Your KSh 10<br /><em>counts.</em></h2><p>Small support from many people creates a powerful path forward for Nakuru. Help us keep the movement open, people-powered, and moving.</p><Link href="/donate" className="button button-primary">Support the movement <span>↗</span></Link></div><div className="support-visual"><img src="/richie-standing-cutout.png" alt="Richie Githatu standing and smiling" /><div><strong>Small support.</strong><br />Big impact.</div></div></div></section>

    <section className="join-cta"><div className="container join-cta-inner"><div><p className="eyebrow">2027 GOVERNOR CAMPAIGN</p><h2>Bring your voice.<br /><em>Choose your future.</em></h2></div><Link href="/join" className="button">Join the movement <span>↗</span></Link></div></section>
  </SiteShell>
}
